# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: images/microphone-alt-solid.ico

# Content configuration version
version: 2

# Personal info
name: Nick Gondek
title: MS Candidate, UChicago Computational Analysis of Public Policy
email: npg@uchicago.edu
# email_title: Email (Email title override)
phone: (414) 581 - 4445
# phone_title: Phone (Phone title override)
website: nickgon.tech
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: gondek_n
github_username: GondekNP

# Additional icon links
additional_links:
- title: Civic Tech 101 Podcast
  icon: images/microphone-alt-solid.ico
  url: https://open.spotify.com/show/0lTfBmiA770Fq604hmcK7T?si=1CNYFqqiRNKcGllAuIIPRA

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/HeadShot.png
about_content: |- # this will include new lines to allow paragraphs
  After first participating in wik

content:
  - title: Education
    layout: list
    content:
      - layout: right
        image: images/CAPP.png
        title: The University of Chicago
        sub_title: Master of Science, Computational Analysis of Public Policy
        location: Markets and Regulation Certificate
        caption: Expected Graduation June 2022
        description: |
        ** Expected Graduation June 2022**
        - Select Coursework
          - _Statistics_: Machine Learning, Advanced Statistics I and II, Program Evaluation, Intermediate Microeconomics, Applied Computer Science I and II, Databases for Public Policy
      - layout: left
        image: images/MINN.png
        title: The University of Minnesota
        sub_title: Bachelors of Science, Dual Major in (1) Fisheries, Wildlife Conservation Biology and (2) Env. Sciences, Policy and Management                          
        location: Magna Cum Laude
        caption: September 2012 - June 2016
        description: |+
          Select Coursework - 
          Biometrics, Mathematical Models of Biological Systems, Honors Financial Reporting,
          Geographical Information Systems, Microeconomics for Natural Resource Management

  - title: Experience
    layout: list
    content:
      - layout: right
        image: images/polsky.png
        title: Polsky Center Technology Commercialization Office
        sub_title: Database Consultant
        location: Chicago, IL (Remote)
        caption: Dec 2020 - Present
        link: polsky.uchicago.edu/tech-commercialization
        quote: >
          "The University of Chicago Polsky Center Technology Commercialization Office manages the intellectual property rights of the University and enables its innovative research to spur novel businesses and commercial ventures."
        description: |
          - Advises on database management best practices and provides consult on the effective transfer of Polsky's intellectual property, business, and contact information to new database software.  
          - Manages a variety of data cleanup projects crucial to the long-term effective function of the Technology Commercial Office's business activities.
          - Reads and researches intellectual property data whilst mantaining security and confidentiality of highly sensitive information. 
      - layout: left
        image: images/CMI.png
        title: Conservation Metrics, Inc.
        sub_title: Acoustic Data Analyst
        location: Santa Cruz, CA
        caption: Jun 2017 – Jun 2020
        link: conservationmetrics.com
        quote: >
          "Conservation Metrics provides automated alternatives to historically labor-intensive wildlife survey efforts, combining cutting-edge remote sensing technology, statistical rigor, and extensive scientific expertise to drive down costs and increase the scale and effectiveness of wildlife metrics."
        description: | 
          - Implemented machine learning approaches (convolutional and deep neural networks) to process data from remote detectors; including microphones, cameras, drones, and satellites.
          - Led in ingestion, analysis, and interpretation of data for frequency of target biological signals in R, Matlab, Python using git-based workflow.
          -	Collaborated with global clients to interpret results for initiatives including invasive rat eradication on Hawadax, novel bat detection in Guinea, comparative methodology studies in northern CA, often developing new strategies to address unexpected challenges.
          - Managed Unix-based network attached storage system of 200+ terabytes of data.
      - layout: right
        title: Hawaii V.I.N.E. Project
        image: images/VINE.png
        sub_title: Avian Research Technician
        location: Oahu, HI
        caption: Oct 2016 – Apr 2017 
        link: www.tarwaterlab.com/hawaii-vine-project
        quote: >
          "The Hawaii V.I.N.E. (Vertebrate Introductions and Novel Ecosystems) Project investigates seed dispersal on Oahu to identify management priorities for local conservation organizations."
        description: | 
          - Captured target passerine species for the purpose of fecal sampling, radio transmitter fixing, and banding.
          - Tracked adult and juvenile birds by way of radiotelemetry and obtained behavioral observations.
          - Sampled invasive and native vegetation for abundance, distribution and phenological activity.
          -	Participated in outreach events with Oahu area students, ranging from 9 to 18 years of age.
      - layout: left
        title: Fieberg Research Lab
        image: images/MINN.png
        sub_title: Honors Researcher
        location: St Paul, MN
        caption: Aug 2015 – Sept 2020 
        link: fieberg-lab.cfans.umn.edu
        quote: >
          "The Fieberg Lab helps widlife biologists make robust statistical inferences when confronted with a variety of messy data situations."
        description: | 
          - Completed an original research project investigating effects of subsampling genetic mark-recapture data using spatially-explicit capture recapture models in R and Program MARK.
          - Authored a reproducible honors thesis document using RMarkdown and LaTeX.
          -	Presented findings to the Minnesota Chapter of the Wildlife Society in Mankato, MN.
      - layout: right
        title: Montana Wildlife Cooperative Research Unit
        image: images/Montana.png
        sub_title: Avian Research Technician
        location: Coconino National Forest, AZ
        caption: May – Aug, 2015 and 2016
        link: umt.edu/mcwru/MartinLab
        quote: >
          "Dr. Martin researches avian behavior to gain an understanding on the ecology and evolution of phenotypic traits that are important to conservation."
        description: | 
          - Captured target passerines of the Coconino National Forest for a 25+ year life history study and a 4+ year metabolic expenditure study along with a team of 30+ researchers.
          - Collaborated with graduate students and principal investigator to gather blood samples, morphological measurements, radio-telemetry based locations, among others.
          -	Transferred data to centralized location each day, processing blood samples into plasma and checking obtained data for mistakes or inconsistencies.

  - title: Communication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
